# Generated by Django 2.1.2 on 2018-10-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Senha', models.CharField(max_length=50)),
                ('Endereco', models.CharField(max_length=50)),
                ('Tipo', models.CharField(max_length=20)),
            ],
        ),
    ]
