# Generated by Django 2.1.2 on 2018-10-29 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoa', '0002_pessoa_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='foto',
            new_name='Foto',
        ),
    ]
