# Generated by Django 2.1.2 on 2018-10-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pessoa', '0003_auto_20181028_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField(default=0)),
                ('Cliente', models.ManyToManyField(blank=True, null=True, to='Pessoa.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Situacao', models.CharField(max_length=30)),
                ('Descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='Status',
            field=models.ManyToManyField(blank=True, null=True, to='loja.Status'),
        ),
    ]
